#!/bin/bash

echo "STCH Library Demo Setup"
echo "-----------------------"
echo "This demo runs entirely in the browser using JavaScript."
echo "It uses Content Delivery Networks (CDNs) for dependencies (TensorFlow.js)."
echo ""
echo "No installation steps are required beyond having a modern web browser."
echo ""
echo "To run the demo:"
echo "1. Ensure you have 'index.html' and 'stch.js' in the same directory."
echo "2. You need to serve these files using a local HTTP server."
echo "   - If you have Python 3: run 'python3 -m http.server 8000' in this directory."
echo "   - If you have Python 2: run 'python -m SimpleHTTPServer 8000' in this directory."
echo "   - If you have Node.js/npm: run 'npx http-server -p 8000 .' in this directory."
echo "   - Alternatively, run the './run.sh' script which tries these automatically."
echo "3. Open your browser and navigate to the address provided (e.g., http://localhost:8000)."
echo ""
echo "Optional Node.js Dependencies (if you wanted to modify/bundle):"
echo "If you were developing this further using Node.js tools, you might install:"
echo "npm install @tensorflow/tfjs # TensorFlow.js library"
# echo "npm install @danfojs/danfojs-node # Danfo.js (if used for analysis)"
echo "npm install http-server --save-dev # For the local server"
echo ""
echo "Setup complete (no action needed)."
